name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.0
      with:
        port: 8888
        cors: '*'

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: ^1.16.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
      env:
        DYNAMOSTORE_DYNAMODB_ENDPOINT: http://127.0.0.1:8888
        DYNAMOSTORE_INTEG_TEST: 'true'
